// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	models "test-assignment/internal/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userID, balance
func (_m *Storage) CreateUser(ctx context.Context, userID int, balance decimal.Decimal) (int, error) {
	ret := _m.Called(ctx, userID, balance)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, decimal.Decimal) (int, error)); ok {
		return rf(ctx, userID, balance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, decimal.Decimal) int); ok {
		r0 = rf(ctx, userID, balance)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, decimal.Decimal) error); ok {
		r1 = rf(ctx, userID, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawal provides a mock function with given fields: ctx, id
func (_m *Storage) GetWithdrawal(ctx context.Context, id int) (models.Withdrawal, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawal")
	}

	var r0 models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Withdrawal, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Withdrawal); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Withdrawal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdrawal provides a mock function with given fields: ctx, userID, withdrawal, idempotencyKey
func (_m *Storage) Withdrawal(ctx context.Context, userID int, withdrawal models.Withdrawal, idempotencyKey string) (models.Withdrawal, error) {
	ret := _m.Called(ctx, userID, withdrawal, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Withdrawal")
	}

	var r0 models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Withdrawal, string) (models.Withdrawal, error)); ok {
		return rf(ctx, userID, withdrawal, idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Withdrawal, string) models.Withdrawal); ok {
		r0 = rf(ctx, userID, withdrawal, idempotencyKey)
	} else {
		r0 = ret.Get(0).(models.Withdrawal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.Withdrawal, string) error); ok {
		r1 = rf(ctx, userID, withdrawal, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
